FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY config.py .
COPY metrics.py .
COPY consumer_service.py .
COPY es-template.json .

# Expose metrics port
EXPOSE 9100

CMD ["python", "consumer_service.py"]
